### ISSUE TITLE
$random 명령어 변경 및 프리픽스 변경

### ISSUE THREAD

**Issue by Re-MoNu** [MisileLab/Happy-AI-Lite-Python#10]
**기능 설명**
$random을 $rng로 바꾸십시오
그리고 제발 프리픽스 바꿔라.
**기능이 필요한 이유**
일단 둘 다 같은 의미이며(오히려 이런 경우에는 rng가 더 맞는 표현이지만) $rng가 더 짧고 빠르고 키끼리 배치도 가까워서 오타가 덜 난다.

제ㅔㅔㅔㅔㅔ발 프리픽스 바꿔주세요. $치기 겁나 불편함 !가 100배는 더 좋음, ?라도 하던가

**Comment by MisileLab** [comment]
프리픽스 변경은 투표로 $를 하는걸로 결정남. $rng는 생각해 보겠음
