### ISSUE TITLE
메세지 삭제 버그(일수도)

### ISSUE THREAD

**Issue by scsmsu** [MisileLab/Happy-AI-Lite-Python#5]
**버그 설명**
클리어 2를 하면 1개만 삭제 됩니다 
+1로 2개 삭제되게 해주세요

**스크린샷**
![image](https://user-images.githubusercontent.com/76481786/108621575-cbdaa900-7476-11eb-9569-91d64fd04b8d.png)

**Comment by MisileLab** [comment]
2.0.1 패치에서 반영
