### ISSUE TITLE
메세지 삭제 로그 삭제

### ISSUE THREAD

**Issue by Re-MoNu** [MisileLab/Happy-AI-Lite-Python#6]
**기능 설명**
메세지 삭제인 ```$clear n```을 쳤을때 ```n개만큼 지웠습니다.```라는 메세지가 잠깐 나오고 사라지게 해주세요

**기능이 필요한 이유**
안 그러면 그 상태에서 다시 ```$clear n```을 쳤을 때 *n-1* 만큼만 지워지는 문제가 발생하고
애초에 채팅방을 **지저분하지 않게** 하려는 명령어의 **목적에 어긋난다.**

**Comment by MisileLab** [comment]
지금 만드는 중입니다 ㄱㄷ

**Comment by MisileLab** [comment]
이제보니 반존댓말이네요ㅋㅋㄹㅋㅋ

**Comment by MisileLab** [comment]
2.0.1 패치에 적용됨.
