### ISSUE TITLE
제발 프리픽스 바꿔주세요

### ISSUE THREAD

**Issue by Re-MoNu** [MisileLab/Happy-AI-Lite-Python#8]
**Is your feature request related to a problem? Please describe.**
진짜 키보드로 $치기 힘들고 내 키보드 특성상 잘 보이지도 않는데, 굳이 $를 쓰나, 어차피 ! 쓰는 봇도 없는데

**Describe the solution you'd like**
프리픽스를 !로 하시오

**Describe alternatives you've considered**
그냥 치기 쉬운거, 예시: . ? / \ ] [ = -

**Version**
내가 어케 알아

**Additional context**
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by MisileLab** [comment]
아이스크림 해피 디코에서 투표 후 결정할거임
