### ISSUE TITLE
파이썬 파일명 변경 요청

### ISSUE THREAD

**Issue by JettaByte-Archive** [MisileLab/Happy-AI-Lite-Python#9]
**Is your feature request related to a problem? Please describe.**
 __init__.py 로 봇의 파일명을 변경할것을 요청합니다.

**Describe the solution you'd like**
이거 패키지로 쓸사람도 있고  __init__.py가 배포에서 제일 좋지 않나여

**Describe alternatives you've considered**
 __init__.py 변경 요망

**Version**
Python Version:3.9

**Additional context**
 __init__.py로 바꾸면 패키지로 쓸거에유

**Comment by MisileLab** [comment]
나중에 제가 패키지로 만들거임

**Comment by JettaByte-Archive** [comment]
머야ㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑㅑ

지금 패키지해줘ㅕㅕㅕㅕㅕㅕㅕㅕㅕㅕㅕㅕㅕㅕㅕㅕㅕㅕㅕㅕ
